### ISSUE TITLE
Plan a module for podman quadlets

### ISSUE THREAD

**Issue by traylenator** [voxpupuli/puppet-quadlets#1]
Here's a rough outline of the module:

## Defined Types

* `quadlets::quadlet_file` as per https://github.com/voxpupuli/puppet-systemd/pull/474
* `quadlets::manage_quadlet`  as per   https://github.com/southalc/podman/pull/83

## Classes
* `quadlet` main class to set things up.
* `quadlet::install` ...

Use existing (or add to) types and classes from systemd module as appropriate.

## Todo

* [ ] Expand README to include breif description of what the modules does with links to quadlets.
* [x] Add standard badges to the README.

**Comment by dabelenda** [comment]
Do you intend to support both types?
They do the same thing but in different ways, the `quadlet_file` I created is a simple "just use raw content" while your `manage_quadlet` allows to check the content if the quadlet.
For me only having `manage_quadlets` is fine, as long as it supports the Kube type for quadlets.

**Comment by dabelenda** [comment]
I can add the support for Kube quadlets on top of your code as soon as you have a PR in this repository.

**Comment by traylenator** [comment]
Happy with just the manage_quadlets then #3 is there just to get something we can build of top of.

**Comment by traylenator** [comment]
Given this is now released this is closed and we can look at finer problems.
